### ISSUE TITLE
Undefined variable "com" or class "com.mysql.jdbc.jdbc2.optional.MysqlDataSource"

### ISSUE THREAD

**Issue by willfurnass** [OpenWaterAnalytics/CANARY#2]
Trying to use a MySQL db as a input datasource but can't connect as `"Undefined variable "com" or class "com.mysql.jdbc.jdbc2.optional.MysqlDataSource"`. From the debug log:

```yaml
- Error:
    timestamp:20150812T132019
    identifier: "MATLAB:undefinedVarOrClass"
    message: "Undefined variable "com" or class "com.mysql.jdbc.jdbc2.optional.MysqlDataSource"."
    Stack:
     - JDBCDataSource.connect @ 94
     - JDBCDataSource.update @ 213
     - pm_timestep @ 292
     - process_message @ 120
     - main @ 159
     - canary @ 204
```

Here's my `.edsy` config file:

```yaml
runMode: BATCH
extraJarFiles:
  - "/usr/share/java/mysql-connector-java-5.1.28.jar"

datasource:
  - id: canarymysqldb
    type      : db
    location  : "jdbc:mysql://127.0.0.1:63306/canary"
    enabled   : yes
    configFile: 
    timestepOpts:  # Ensure that the values you want are enclosed by "-quotes
      field      : "TIME_STEP"
      format     : "%Y-%m-%d %H:%i:%s"
      convertFunc: "str_to_date"
    databaseOpts:
      ...
      className  : "com.mysql.jdbc.jdbc2.optional.MysqlDataSource"
      ...
```

FYI I'm using CANARY 4.3.2 (b26:r3874, 2013-10-02, 09:11:24, built using MATLAB 8.1.0.604 (R2013a)).  `mysql-connector-java-5.1.28.jar` is from the Ubuntu 14.04 `libmysql-java` package.

**Comment by willfurnass** [comment]
Same result when using
```yaml
 - extraJarFiles:  [ '/usr/share/java/postgresql-jdbc3-9.2.jar' ]
 - className: 'org.postgresql.Driver'
 - location: "jdbc:postgresql://localhost:5432/canarydb"
```

plus the `libpostgresql-jdbc-java` 9.2-1002-1 and `postgresql` 9.3+154ubuntu1 Ubuntu Trusty packages
