### ISSUE TITLE
SQL string literals not properly quoted when 'output format: "row based"'

### ISSUE THREAD

**Issue by willfurnass** [OpenWaterAnalytics/CANARY#3]
From the `debug.sql` file:

```sql
SELECT TIME_STEP, TAG_NAME, VALUE 
FROM samples 
WHERE (TIME_STEP > STR_TO_DATE('2012-02-15 13:45','%Y-%m-%d %H:%i:%s')
AND TIME_STEP <= STR_TO_DATE(    '2012-02-16 14:00','%Y-%m-%d %H:%i:%s')
AND TAG_NAME = RESQ1_FLOW_VAL )
ORDER BY TIME_STEP
```

With 'row-based' output, `RESQ1_FLOW_VAL` is a string literal in the TAG_NAME colum, *not* a column name, so **needs to be enclosed within single quotes**.  

A workaround to this problem is to use nested quotes around the SCADA ID of signals in the `.edsy` file like this:

```yaml
# Enter the list of SCADA/composite signals/parameters below
signal:
- id: FLOW_VAL
  SCADATag: "'RESQ1_FLOW_VAL'"

FYI I'm using CANARY 4.3.2 (b26:r3874, 2013-10-02, 09:11:24, built using MATLAB 8.1.0.604 (R2013a)) and MySQL JDBC driver 5.1.28.
```
